### ISSUE TITLE
project review

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Thermostat#2]
@hartytp @jordens I sketched first release.
Please have a look at it.
I also updated wiki with drawings.

**Comment by jordens** [comment]
Nice!
1. I'd hook up the ENABLE pins to the uC plus pulldowns and alternatively 0R to GND.
2. You might want to check the output capacitor of the PoE module. They have 470µF there.
3. We need to check that we meet maintain power signature on PoE. That's a couple hundred mW mimimum power consumption IIRC. We should also avoid the acoustic noise the PoE module DS talks about when it runs at low power.
4. Isn't it more efficient to send 5V (instead of 12V) to the other board with the extension channels? The step-down module can handle it and the PoE module as well. You could even use one of those board-to-board edge connectors that you found for Sensor-Box.
5. Can we hook up the LED outputs of the wiznet module to the RJ45 jack LEDs as well?
6. Any chance we can connect pins 15 and 16 (I2C) of the Zotino-TEC connectors to the µC?
9. I'd explicitly pull up RESET of the wiznet module.
7. Congrats to squeezing it on two layers!

**Comment by hartytp** [comment]
@gkasprow Great! Travelling atm but will probably be able to look at this in the next few days.

**Comment by gkasprow** [comment]
@jordens I implemented all changes. Thanks for review. The connectors I use in my sensorbox project  would collide with extruded enclosure so I left IDCs.

**Comment by hartytp** [comment]
Thanks for that @gkasprow !

- nit picking a bit, but it would be nice to zero-index everything on this board to be consistent with other designs 
- should the P12V lines from Zotino be connected via DNF 0R resistors?
- probably not worth changing now, but I thought we had agreed to drop support for 12V supply (from Zotino and front panel) and use 5V from PoE (IIRC, there was a 5V version of the PoE module). That would simplify the design and improve the efficiency. In any case, it's probably not a good idea to supply a TEC from the 12V Kasli supply, so maybe we shouldn't even offer this...
- what's the 4-channel extension?

I haven't done a thorough design review for the PoE, microprocessor and Ethernet parts of the circuit, but other than that, all looks good!

**Comment by gkasprow** [comment]
4-channel extension lets you control second module equipped with just TEC controllers from first module with Ethernet, PoE and DC/DC. I'm a bit afraid of exposing 5V to the panel. Someone may plug 12V supply by chance since other EEMs offer such ability.

**Comment by hartytp** [comment]
> 4-channel extension lets you control second module equipped with just TEC controllers from first module with Ethernet, PoE and DC/DC.

Okay, makes sense. Have you designed this board yet? Is it worth doing this? IMHO, if people need 4 channels, it's easier to just have two identical thermostat cards with separate ethernet/PoE connections, instead of having to have two separate (non-identical) boards. So, I'd be tempted to scrap this, although I don't feel strongly about it.

Also, is there enough power from the PoE module to run 4 TECs safely?

> I'm a bit afraid of exposing 5V to the panel. Someone may plug 12V supply by chance since other EEMs offer such ability.

I meant removing the barrel connector completely and only supporting PoE (I thought this is what we had agreed before). PoE injectors are pretty cheap, so I don't see much need to support both PoE and barrel connectors.

**Comment by gkasprow** [comment]
@hartytp It is the same board, but without PoE and Ethernet module.
PoE is rated for 35W

**Comment by hartytp** [comment]
sounds good then.

One final request: could you add a comment on the schematic with the p/n (and mating p/n) for those din connectors, please? That way I don't have to load the Altium files to figure it out.

**Comment by jordens** [comment]
[These](http://www.farnell.com/datasheets/48895.pdf) enclosures might also be nice. You can use the same panels. Also for remote Zotino breakout-boxes with a couple VHDCI-IDC and IDC-BNC.

**Comment by hartytp** [comment]
Good find. If you use them, let me know how they work out.

**Comment by gkasprow** [comment]
@jordens I use them in the lab. I already posted [pics ](https://github.com/sinara-hw/sinara/issues/188#issuecomment-327180612) with them some time ago :) They are really nice.

**Comment by hartytp** [comment]
@gkasprow did you ever produce any Thermostat prototypes? I'd like some if they're going :)

**Comment by gkasprow** [comment]
Not yet, I'm collecting designs to spare on NRE costs. I will produce it together with Banker extension boards.

**Comment by hartytp** [comment]
Good plan. I'm not in a massive hurry for this, but it would be nice to have at some point.

**Comment by hartytp** [comment]
Closing this issue since I think the design review is now complete

**Comment by jordens** [comment]
Ah. Nice!
